import Head from "next/head";
import { useState } from "react";
import { Document, Page, pdfjs } from "react-pdf";
import useMediaQuery from "@mui/material/useMediaQuery";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;
//component imports
import Navbar from "../components/navbar";
import ContactMe from "../components/contactMe";
import Footer from "../components/footer";

export default function Resume() {
  const isInitialRequestGreaterThan700 = useMediaQuery("(min-width:700px)");
  return (
    <div className="bg-black">
      <Head>
        <title>Elroy Chua Portfolio - Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/elroy_icon.png" />
      </Head>
      <Navbar activePage="resume" />
      <main className="flex flex-col ">
        {isInitialRequestGreaterThan700 ? (
          <section
            className="flex flex-col justify-around pt-10 px-10 md:px-20 lg:px-40 max-w-7xl self-center"
            style={{ height: "calc(100vh - 140px)" }}
          >
            <div
              style={{ maxWidth: "100%", width: "100%", padding: "10px" }}
              className="bg-slate-900 rounded-xl shadow-xl"
            >
              <h2 className="font-mono bg-clip-text text-emerald-400 py-2 text-left  text-2xl md:text-5xl">
                Resume
              </h2>
              <p className="font-mono bg-clip-text text-white py-2 text-left  text-lg md:text-xl">
                Available as per request. Hit me up on any of my socials below!
              </p>
            </div>
            <div>
              <ContactMe />
              <Footer />
            </div>
          </section>
        ) : (
          <section className="flex flex-col justify-around pt-10 px-10 md:px-20 lg:px-40 max-w-7xl self-center">
            <div
              style={{ maxWidth: "100%", width: "100%", padding: "10px" }}
              className="bg-slate-900 rounded-xl shadow-xl"
            >
              <h2 className="font-mono bg-clip-text text-emerald-400 py-2 text-left  text-2xl md:text-5xl">
                Resume
              </h2>
              <p className="font-mono bg-clip-text text-white py-2 text-left  text-lg md:text-xl">
                Available as per request. Hit me up on any of my socials below!
              </p>
            </div>
            <div>
              <ContactMe />
              <Footer />
            </div>
          </section>
        )}
      </main>
    </div>
  );
}
