import Head from "next/head";
import { AiFillGithub } from "react-icons/ai";
import Navbar from "../../components/navbar";
import Footer from "../../components/footer";
import ContactMe from "../../components/contactMe";
export default function ProjectPage() {
  return (
    <div className="bg-slate-900">
      <Head>
        <title>Elroy Chua Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/elroy_icon.png" />
      </Head>
      <Navbar activePage="project" />
      <main className="flex flex-col">
        <section className="p-10 md:px-20 lg:px-40 max-w-7xl self-center">
          <Project />
        </section>
        <section className=" px-10 md:px-20 lg:px-40 max-w-7xl self-center">
          <ContactMe />
          <Footer />
        </section>
      </main>
    </div>
  );
}

const Project = () => {
  return (
    <section>
      <div>
        <div className="group font-mono text-4xl font-bold text-white py-1 mt-8 flex flex-row">
          <span className="bg-left-bottom bg-gradient-to-r from-teal-400 to-teal-400 bg-[length:0%_2px] bg-no-repeat group-hover:bg-[length:100%_2px] transition-all duration-500 ease-out">
            Appetizer Hackathon 2023
          </span>
          <div className="self-center text-center cursor-pointer hover:text-teal-400 ml-8">
            <a
              href="https://github.com/D2HD/getgoing-application"
              target="blank"
            >
              <AiFillGithub />
            </a>
            <p className="text-xs">github</p>
          </div>
        </div>

        <div className="group font-mono text-2xl font-bold text-white py-1 mt-8">
          Introduction
        </div>
        <p className="text-sm md:text-md py-2 leading-8 text-white">
          Implement cloud-based solutions using the Twitter Hash scraper API and
          engineered a full-stack application that tackled challenges arising
          from the COVID-19 pandemic and achieving the third prize in the 2023
          Appetizer Global Hackathon.
        </p>
        <div className="group font-mono text-2xl font-bold text-white py-1 mt-4">
          Solution
        </div>
        <p className="text-sm md:text-md py-2 leading-8 text-white">
          Frontend was developed using ReactJS and NextJS, rendering information
          from Hashscraper and displaying it through Axios dependency, while
          creating interactive user interface components for data visualization.
          On the backend, we utilized Spring and Heroku Postgres, implementing
          logic to utilize the Hashscraper API and provide internal API features
          for the frontend.
        </p>
        <div className="group font-mono text-2xl font-bold text-white py-1 mt-4 mb-2">
          Walkthrough Video
        </div>
        <div className="container">
          <iframe
            className="responsive-main-iframe"
            src="https://drive.google.com/file/d/1PrOYrg5yae2OcmXIFxpajWa9TXHqv19J/preview"
          ></iframe>
        </div>

        <div className="group font-mono text-2xl font-bold text-white py-1 mt-4 mb-2">
          Features:
        </div>
        <div className="flex flex-col xl:flex-row mt-0 lg:mt-16">
          <div className="p-0 md:p-4 mr-4">
            <div className="group font-mono text-xl font-bold text-white py-1 mt-6 md:mt-0">
              <span className="bg-left-bottom bg-gradient-to-r from-blue-500 to-blue-500 bg-[length:0%_2px] bg-no-repeat group-hover:bg-[length:100%_2px] transition-all duration-500 ease-out">
                A. Free Account
              </span>
            </div>
            <p className="text-sm md:text-md  py-2 leading-8 text-white">
              This feature requires an account with the optionality to upgrade
              and offers the display of the top 5 hashtags, search trends for
              daily and weekly tweets exclusively, data visualizations for
              tweets, and updates on a weekly cycle.
            </p>
          </div>
          <div className=" flex justify-center">
            <iframe
              className="responsive-sub-iframe"
              src="https://drive.google.com/file/d/1wTidnoCTbYZ3oPmcJ8qihJObPhia-Vtw/preview"
              width="440"
              height="247.5"
              allow="autoplay"
            ></iframe>
          </div>
        </div>

        <div className="flex flex-col-reverse xl:flex-row mt-0 lg:mt-16">
          <div className="p-4 mr-4 flex justify-center">
            <iframe
              className="responsive-sub-iframe"
              src="https://drive.google.com/file/d/1wTidnoCTbYZ3oPmcJ8qihJObPhia-Vtw/preview"
              width="440"
              height="247.5"
              allow="autoplay"
            ></iframe>
          </div>
          <div className="p-0 md:p-4">
            <div className="group font-mono text-xl font-bold text-white py-1 mt-6 md:mt-0">
              <span className="bg-left-bottom bg-gradient-to-r from-blue-500 to-blue-500 bg-[length:0%_2px] bg-no-repeat group-hover:bg-[length:100%_2px] transition-all duration-500 ease-out">
                B. Premium Account
              </span>
            </div>
            <p className="text-sm md:text-md  py-2 leading-8 text-white">
              This feature offers access to search engine functionality, shows
              search trends for daily and weekly including tweets, retweets,
              likes, and sentiment counts, displays data visualizations for
              tweets, retweets, likes, hashtags, and sentiment counts, updates
              in real time, and is available via a monthly subscription.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};
