import Head from "next/head";
import dynamic from "next/dynamic";
import { RiCopyrightFill } from "react-icons/ri";
import Navbar from "../public/components/navbar";
import Hero from "../public/components/hero";
import AboutMe from "../public/components/aboutMe";
import WorkExperience from "../public/components/workExp";
import Projects from "../public/components/projects";
const ProjectCarousel = dynamic(
  () => import("../public/components/projectCarousel"),
  { ssr: false }
);
import ContactMe from "../public/components/contactMe";
import Footer from "../public/components/footer";
import * as React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Elroy Chua Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/elroy_icon.png" />
      </Head>
      <Navbar activePage="home" />
      <main>
        <section className=" bg-white pt-12 px-10 md:px-20 lg:px-40">
          <Hero />
          <AboutMe />
          <WorkExperience />
          <Projects />
        </section>
        <section>
          <ProjectCarousel />
        </section>
        <section className=" bg-white px-10 md:px-20 lg:px-40 ">
          <ContactMe />
          <Footer />
        </section>
      </main>
    </>
  );
}
