import Head from "next/head";
import { RiCopyrightFill } from "react-icons/ri";
import Navbar from "../public/components/navbar";
import Hero from "../public/components/hero";
import AboutMe from "../public/components/aboutMe";
// import Skills from "../public/components/skills";
import WorkExperience from "../public/components/workExp";
import Projects from "../public/components/projects";
import ScrollToTop from "../public/components/scrollToTop";
import ContactMe from "../public/components/contactMe";
import Footer from "../public/components/footer";
import * as React from "react";

export default function Home() {
  return (
    <div className="bg-slate-900">
      <Head>
        <title>Elroy Chua Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/elroy_icon.png" />
      </Head>
      <Navbar activePage="home" />
      <main className="flex flex-col">
        <section className="p-10 md:px-20 lg:px-40 max-w-7xl self-center">
          <Hero />
          <AboutMe />
          {/* <Skills /> */}
          <WorkExperience />
          <Projects />
          <ContactMe />
          <Footer />
          <ScrollToTop />
        </section>
      </main>
    </div>
  );
}
