import Head from "next/head";
import Navbar from "../public/components/navbar";
import Hero from "../public/components/hero";
import AboutMe from "../public/components/aboutMe";
import WorkExperience from "../public/components/workExp";
export default function Home() {
  return (
    <>
      <Head>
        <title>Elroy Chua Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/elroy_icon.png" />
      </Head>
      <Navbar />
      <main className=" bg-white px-10 md:px-20 lg:px-40">
        <Hero />
        <AboutMe />
        <WorkExperience />
        <section>
          <div className=" h-32"></div>
          <div>
            <h3 className="text-3xl py-1">Projects</h3>
            <p className="py-2"></p>
          </div>
          <div></div>
        </section>
      </main>
    </>
  );
}
