import Head from "next/head";
import Navbar from "../public/components/navbar";
import * as React from "react";
import { useState } from "react";
import { Document, Page, pdfjs } from "react-pdf";
import useMediaQuery from "@mui/material/useMediaQuery";
pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.js`;

export default function Resume() {
  const [numPages, setNumPages] = useState(null);
  const [pageNumber, setPageNumber] = useState(1);

  function onDocumentLoadSuccess({ numPages }) {
    setNumPages(numPages);
  }
  const canvasWrapperStyle = {
    backgroundColor: "#f0f0f0",
    border: "1px solid black",
    borderRadius: "5px",
    padding: "10px",
  };
  const isInitialRequestGreaterThan700 = useMediaQuery("(min-width:700px)");
  return (
    <>
      <Head>
        <title>Elroy Chua Portfolio - Resume</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/elroy_icon.png" />
      </Head>
      <Navbar />
      <main>
        <section className=" bg-white px-10 md:px-20 lg:px-40">
          <div
            className="text-center"
            style={{ maxWidth: "100%", width: "100%" }}
            options={{ workerSrc: "/pdf.worker.js" }}
          >
            <Document
              file="ElroyChuaResume.pdf"
              onLoadSuccess={onDocumentLoadSuccess}
              canvasWrapperStyle={canvasWrapperStyle}
            >
              {isInitialRequestGreaterThan700 ? (
                <Page
                  pageNumber={pageNumber}
                  renderAnnotationLayer={false}
                  renderTextLayer={false}
                  width="600"
                />
              ) : (
                <Page
                  pageNumber={pageNumber}
                  renderAnnotationLayer={false}
                  renderTextLayer={false}
                  width="300"
                />
              )}
            </Document>
            <p>
              Page {pageNumber} of {numPages}
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
